name: Run Script

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: '* 23 * * *'
jobs:
  add_maps:
    name: Add Maps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: azerus-team/.github
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.REPO_DIR }}

    - name: run
      run: python ${{ env.REPO_DIR }}/auto_readme.py
      shell: sh
