name: Run Script

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: '* 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          python-version: 3.10 # install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python auto_readme.py
